### ISSUE TITLE
Dependency does not exist?

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js-nativescript#1]
See https://github.com/ably/ably-nativescript/blob/master/ably.js#L2 and https://github.com/ably/ably-nativescript/blob/master/package.json#L15, you're referencing a dependency that as far as I can tell does not exist, see https://github.com/ably/ably-js/releases

**Comment by NathanaelA** [comment]
Sorry, I assumed that by Beta.5 the pull request would already have been accepted.   Which ever BETA.x the https://github.com/ably/ably-js/pull/362 is accepted in will be when the package.json in this will be updated to.   :-)

**Comment by SimonWoolf** [comment]
Updated the ably-js dep to `~0.9.0-beta.6`, which has the nativescript support PR
