### ISSUE TITLE
Use ably-js repo typings

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-js-nativescript#3]
@NathanaelA There's now a typescript definitions file in the ably-js repo https://github.com/ably/ably-js/blob/master/ably.d.ts ; would it be possible for nativescript to use that, so we only have one definitions file to keep in sync with ably-js changes? (They seem to be in slightly different formats atm (the ably-js one uses a namespace) so not sure if there's any work needed before nativescript can use it)

**Comment by NathanaelA** [comment]
You can use whichever typescript definitions you prefer to use.    ;-)        If you prefer this one; you will need to make sure the NativeScript plugin build step copies them from that folder into the folder that is used to build the NPM .tgz file, that way you are only maintaining the master copy.

---
This comment above is incorrect; I was thinking there was a build step for NS; but we are linking to the main `ably` as a npm dependency, the only build step is when building the ably code in the main repo which doesn't need to worry about typings...

**Comment by SimonWoolf** [comment]
@NathanaelA thanks -- so to be clear, you're saying it wouldn't work to just reference it (under the assumption that the main lib is in a `node_modules` folder)? I.e. I can't just put `"typings": "node_modules/ably/ably.d.ts"` in the package.json?

**Comment by NathanaelA** [comment]
The typings path actually should be "../ably/ably.d.ts" as the plugin is looking for the ably.js file to be in the main nodemodules -- folder also...

**Comment by mattheworiordan** [comment]
The `ably-js` TS file is the one we should be using.  I found lots of issues in the TypeScript files when I tried it out, see https://github.com/ably/ably-js/pull/376 (note that it was previously named `ably.ts.d` which is also wrong i.e. that's not even a TS extension)

**Comment by NathanaelA** [comment]
@mattheworiordan - 
1. Agreed, looks like I did a typo, should have been `.d.ts`  
2. That is what Simon and I were discussing, switching to a single version I just was fixing his path -- it should not be `node_modules/ably/ably.d.ts` it should be `../ably/ably.d.ts` for it to work in npm 3+ since it now flattens the npm module structure.
3. When he does that change; he should just remove this typings file from this repo to eliminate any confusion.

**Comment by SimonWoolf** [comment]
good point, thanks! Made that change, let me know if it causes any tests to break. Cheers
